### ISSUE TITLE
Plugin doesn't work in Grafana:  v7.4.0-beta1

### ISSUE THREAD

**Issue by DanTulovsky** [lightstep/lightstep-grafana-plugin#81]
I installed the plugin in Grafand  v7.4.0-beta1 and enabled it.  When I try to add a datasource, clicking the 'Save and Test' button produces an error:

```
An unexpected error happened
DetailsError: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bstatus%2C%20statusText%2C%20data%2C%20config%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

    at div
    at div
    at div
    at https://grafana.wetsnow.com/public/build/app.2f8a2e0c61d1da0c631f.js:2:46678
    at div
    at form
    at div
    at div
    at t (https://grafana.wetsnow.com/public/build/app.2f8a2e0c61d1da0c631f.js:2:1644311)
    at div
    at div
    at div
    at t (https://grafana.wetsnow.com/public/build/vendors~app.2f8a2e0c61d1da0c631f.js:2:1000310)
    at t (https://grafana.wetsnow.com/public/build/app.2f8a2e0c61d1da0c631f.js:2:2976327)
    at div
    at t (https://grafana.wetsnow.com/public/build/app.2f8a2e0c61d1da0c631f.js:2:1646395)
    at t (https://grafana.wetsnow.com/public/build/DataSourceSettingsPage.2f8a2e0c61d1da0c631f.js:1:7235)
    at S (https://grafana.wetsnow.com/public/build/vendors~app.2f8a2e0c61d1da0c631f.js:2:84308)
    at ConnectWithCleanUp(Connect(t)) (https://grafana.wetsnow.com/public/build/DataSourceSettingsPage.2f8a2e0c61d1da0c631f.js:1:12727)
    at n (https://grafana.wetsnow.com/public/build/vendors~app.2f8a2e0c61d1da0c631f.js:2:624003)
    at t (https://grafana.wetsnow.com/public/build/app.2f8a2e0c61d1da0c631f.js:2:1727466)
    at h (https://grafana.wetsnow.com/public/build/app.2f8a2e0c61d1da0c631f.js:2:2901862)
    at t (https://grafana.wetsnow.com/public/build/app.2f8a2e0c61d1da0c631f.js:2:1884638)
    at t (https://grafana.wetsnow.com/public/build/app.2f8a2e0c61d1da0c631f.js:2:1885168)
    at l (https://grafana.wetsnow.com/public/build/vendors~app.2f8a2e0c61d1da0c631f.js:2:82216)
```

which seems to decode to:

```
Objects are not valid as a React child (found: object with keys {status, statusText, data, config}). If you meant to render a collection of children, use an array instead.
```

**Comment by chrisleavoy** [comment]
I ran into a similar issue.  Grafana doesn't handle the save/test button failing for LightStep data source and produces the above.  After I fixed my incorrect usage of an "Access Token" where Grafana wants an "API token", I stopped getting a 403 error and save button worked.

**Comment by DanTulovsky** [comment]
Oh.. :)  Thank you, that was it.  It did, in fact, want a user API Key in there.  Works fine now.
